"""initial multi tenant schema with pgvector

Revision ID: 328787185122
Revises:
Create Date: 2026-09-21 22:26:47.689738
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "328787185122"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # pgvector must exist before any column can use the vector type. Safe to
    # run every time: CREATE EXTENSION IF NOT EXISTS is a no-op on a database
    # that already has it, which is the normal case for every migration
    # after this first one.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "red_team_result",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("suite", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("case_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("detail", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workspace",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conversation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_workspace_id"), "conversation", ["workspace_id"], unique=False
    )
    op.create_table(
        "document",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sha256", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column(
            "extraction_method",
            sa.Enum("TEXT", "OCR", "MIXED", name="extraction_method"),
            nullable=False,
        ),
        sa.Column("uploaded_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_document_sha256"), "document", ["sha256"], unique=False)
    op.create_index(op.f("ix_document_workspace_id"), "document", ["workspace_id"], unique=False)
    op.create_table(
        "eval_question",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("question", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expected_chunk_ids", sa.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "DIRECT",
                "BOUNDARY",
                "TABLE",
                "CROSS_DOCUMENT",
                "OUT_OF_SCOPE",
                "INJECTION",
                name="eval_category",
            ),
            nullable=False,
        ),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_eval_question_category"), "eval_question", ["category"], unique=False)
    op.create_index(
        op.f("ix_eval_question_workspace_id"), "eval_question", ["workspace_id"], unique=False
    )
    op.create_table(
        "eval_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("embedding_backend", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rerank_backend", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("config_label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("recall_at_3", sa.Float(), nullable=False),
        sa.Column("recall_at_5", sa.Float(), nullable=False),
        sa.Column("precision_at_5", sa.Float(), nullable=False),
        sa.Column("mrr", sa.Float(), nullable=False),
        sa.Column("n_questions", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_eval_run_workspace_id"), "eval_run", ["workspace_id"], unique=False)
    op.create_table(
        "chunk",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("strategy", sa.Enum("NAIVE", "STRUCTURE", name="chunk_strategy"), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("page_start", sa.Integer(), nullable=False),
        sa.Column("page_end", sa.Integer(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("section_title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column("embedding_backend", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("injection_flag", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chunk_document_id"), "chunk", ["document_id"], unique=False)
    op.create_index(op.f("ix_chunk_strategy"), "chunk", ["strategy"], unique=False)
    op.create_index(op.f("ix_chunk_workspace_id"), "chunk", ["workspace_id"], unique=False)
    op.create_table(
        "turn",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("question", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("retrieved_chunk_ids", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("reranked", sa.Boolean(), nullable=False),
        sa.Column(
            "chunking_strategy",
            sa.Enum("NAIVE", "STRUCTURE", name="turn_chunk_strategy"),
            nullable=True,
        ),
        sa.Column("answer", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("claims", sa.JSON(), nullable=True),
        sa.Column("citation_verifications", sa.JSON(), nullable=True),
        sa.Column("extractive_fallback", sa.Boolean(), nullable=False),
        sa.Column("judge_scores", sa.JSON(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_turn_conversation_id"), "turn", ["conversation_id"], unique=False)
    op.create_index(op.f("ix_turn_workspace_id"), "turn", ["workspace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_turn_workspace_id"), table_name="turn")
    op.drop_index(op.f("ix_turn_conversation_id"), table_name="turn")
    op.drop_table("turn")
    op.drop_index(op.f("ix_chunk_workspace_id"), table_name="chunk")
    op.drop_index(op.f("ix_chunk_strategy"), table_name="chunk")
    op.drop_index(op.f("ix_chunk_document_id"), table_name="chunk")
    op.drop_table("chunk")
    op.drop_index(op.f("ix_eval_run_workspace_id"), table_name="eval_run")
    op.drop_table("eval_run")
    op.drop_index(op.f("ix_eval_question_workspace_id"), table_name="eval_question")
    op.drop_index(op.f("ix_eval_question_category"), table_name="eval_question")
    op.drop_table("eval_question")
    op.drop_index(op.f("ix_document_workspace_id"), table_name="document")
    op.drop_index(op.f("ix_document_sha256"), table_name="document")
    op.drop_table("document")
    op.drop_index(op.f("ix_conversation_workspace_id"), table_name="conversation")
    op.drop_table("conversation")
    op.drop_table("workspace")
    op.drop_table("red_team_result")
    # ### end Alembic commands ###
